### ISSUE TITLE
Keeping Modernizr up to date

### ISSUE THREAD

**Issue by mmarol** [risd/webhook-template#2]
@rubillionaire I just had to manually update the modernizr version, but it seems a little ridiculous to check every time a new site is made if there is a new version.
I was thinking of having grunt compile another js file that goes into the `base.html` head that just contains modernizr, or possibly other scripts that would have to run before the body. Thoughts?

**Comment by rubillionaire** [comment]
Ah yes, modernizr and other head scripts are squirrelly.
- What prompted the need to update modernizr? 
- Every dependency that one gets via `npm install` is also pinned to a version, or a range of versions. So eventually everything gets out of date. Which I don't see as a problem in and of itself. If it has negative side effects on the project, or its ability to be developed, then I would say its a problem worth correcting.
- Having another grunt process build a `head.js` file, would be cool.
- Modernizer, and other head scripts are worth making as small as possible. The best practice I have come to adopt is to only include Modernizr if the project uses it. And to include a version that is built specifically for that site, based on the features of Modernizr that are being used. I don't see being about the latest version, so much as one that functions as needed, with no overhead.
